### ISSUE TITLE
能不能整理个pdf版本

### ISSUE THREAD

**Issue by wjx0912** [xg-wang/gobyexample#30]
感谢

**Comment by everyx** [comment]
你好，这个项目已经年久失修了，深感抱歉，目前共工作很忙，也没有时间处理相关事宜，不知道你有没有兴趣接手这个翻译项目？目前存在一些翻译的 bug 需要修正。

如果要做成 pdf 的话，做好的方法是使用 gitbook 的 hosts 服务（而且需要科学上网），不过这个项目需要重写为 md 版本的。

如果你时间充足并且希望继续提升这个版本的翻译体验，欢迎联系我

**Comment by wjx0912** [comment]
@everyx 
我才刚学go不久。。。水平涨一点后再来做贡献吧。辛苦你们了~~
