### ISSUE TITLE
中文版网页访问不稳定，时常弹出下载框

### ISSUE THREAD

**Issue by maijianhu** [xg-wang/gobyexample#42]
感谢提供中文版翻译！
服务器的访问时常有些问题，点击每个例子的页面有时并不会进入页面，而是弹出下载框，会不会是web服务器response没有设置好呢？

**Comment by xg-wang** [comment]
抱歉，感觉firebase最近改了对于静态不加html后缀文件的请求header，我现在改成访问xxx.html应该可以正常访问啦。可以清掉缓存刷新一下试试。
